#!/usr/bin/python

import sys
import xmltodict

with open(sys.argv[1], 'r') as file:
    while file.readline().rstrip('\n\r'):
        pass

    xml = xmltodict.parse(file.read())

headers = []

transactions = xml['OFX']['BANKMSGSRSV1']['STMTTRNRS']['STMTRS']['BANKTRANLIST']['STMTTRN']
for entry in transactions:
    for header in entry:
        if header not in headers:
            headers.append(header)

print ','.join(headers)
for trx in transactions:
    print ','.join(trx.get(h, '') for h in headers)
