#!/usr/bin/python

import sys
import xmltodict

with open(sys.argv[1], 'r') as file:
    while file.readline().rstrip('\n\r'):
        pass

    xml = xmltodict.parse(file.read())


headers = []
entries = []

for trx in xml['OFX']['BANKMSGSRSV1']['STMTTRNRS']['STMTRS']['BANKTRANLIST']['STMTTRN']:
    for header in trx:
        if header not in headers:
            headers.append(header)
    entries.append(trx)

print ','.join(headers)
for entry in entries:
    print ','.join(entry.get(h, '') for h in headers)
